name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@v0.4
    with:
      node-version: 24
      build-script: package
      test-script: test
      build: false
